apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-sq5u
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-sq5u
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-sq5u
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-sq5u
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-sq5u
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-ognh-tenant/status-quarkus-io/statusquarkusio-sq5u@sha256:7d0a0ba775019c5db61a12cdcb95cd05048b3a4e2ee704b506e73a4358c6a3ca
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
